export interface Contracts {
    RoleStore?: string | undefined;
    DataStore?: string | undefined;
    EventEmitter?: string | undefined;
    OracleStore?: string | undefined;
    Pragma?: string | undefined;
    Oracle?: string | undefined;
    OrderVault?: string | undefined;
    SwapHandler?: string | undefined;
    ReferralStorage?: string | undefined;
    IncreaseOrderUtils?: string | undefined;
    DecreaseOrderUtils?: string | undefined;
    SwapOrderUtils?: string | undefined;
    OrderUtils?: string | undefined;
    OrderHandler?: string | undefined;
    DepositVault?: string | undefined;
    DepositHandler?: string | undefined;
    WithdrawalVault?: string | undefined;
    WithdrawalHandler?: string | undefined;
    MarketFactory?: string | undefined;
    Reader?: string | undefined;
    Router?: string | undefined;
    ExchangeRouter?: string | undefined;
}
