[env]
NET = 'sepolia'
PROVIDER_URL = 'https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/eVJH-YcwoFpbl98OYbKvvzMGTP730kd1'
ACCOUNT_PUBLIC = ''
ACCOUNT_PRIVATE = ''
FEE_TOKEN = ''
WSS_PROVIDER_URL = 'wss://endpoints.omniatech.io/v1/ws/starknet/sepolia/ea0f93955c4f44548b4a4fb64973723c'
HERMES_URL = 'https://hermes-beta.pyth.network'

INDEXER_PORT = 3001
DATABASE_URL = 'postgresql://{user}:{password}@localhost:5432/sepolia_checkpoint'
