app = 'freyr-keeper-sepolia'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

  [build.args]
    NET = 'sepolia'

[http_service]
  internal_port = 3001
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
