scalar UInt256

type Order {
    id: ID!
    author: String!
    key: String!
    market: String!
    order_type: String!
    is_long: Boolean!
    index_token_address: String!
    trigger_price: UInt256!
    acceptable_price: UInt256!
    is_executed: Boolean!
    tx_hash: String!
    created_at: Int!
    created_at_block: Int!
}

type Position {
    id: ID!
    author: String!
    key: String!
    market: String!
    is_long: Boolean!
    collateral_amount: String!
    collateral_token: String!
    size_in_usd: UInt256!
    size_delta_usd: UInt256!
    size_in_tokens: UInt256!
    is_closed: Boolean!
    is_liquidated: Boolean!
    tx_hash: String!
    created_at: Int!
    created_at_block: Int!
}
