scalar UInt256

type Order {
    id: ID!
    account: String!
    action: Int
    key: String!
    market: String!
    order_type: String!
    is_long: Boolean!
    initial_collateral_token: String!
    index_token_address: String!
    size_delta_usd: UInt256!
    trigger_price: UInt256!
    acceptable_price: UInt256!
    tx_hash: String!
    created_at: Int!
    created_at_block: Int!
}

type Position {
    id: ID!
    account: String!
    key: String!
    market: String!
    is_long: Boolean!
    collateral_amount: String!
    collateral_token: String!
    size_in_usd: UInt256!
    size_delta_usd: UInt256!
    size_in_tokens: UInt256!
    tx_hash: String!
    created_at: Int!
    created_at_block: Int!
}

type TradeHistory {
    id: ID!
    account: String!
    key: String!
    action: Int!
    market: String!
    is_long: Boolean!
    order_size_usd: UInt256 # for Order
    order_price: UInt256 # for Order
    deposit_long_token_amount: UInt256 # for Deposit
    deposit_short_token_amount: UInt256 # for Deposit
    pool_market_token_amount: UInt256 # for Deposit and Withdrawal
    tx_hash: String!
    created_at: Int!
    created_at_block: Int!
}
